import { Question } from "../types";

/**
 * Second-wave curated seeds (Fase 1 — riequilibrio §7.2).
 * One multi-choice + one free-text per syllabus block to strengthen
 * the deficit types with manually verified quality. IDs use the
 * B*-SEED-* namespace to avoid collisions with existing seeds.
 */
export const additionalSeedQuestions: Question[] = [
  // ---------------- Blocco 1 ----------------
  {
    id: "B1-SEED-MC-101",
    version: 1,
    block: 1,
    topic: "tradeoff-costo-opportunita",
    tags: ["trade-off", "costo-opportunita", "decisioni"],
    track: "essential",
    difficulty: 2,
    type: "multi-choice",
    stem: "Quali affermazioni distinguono correttamente il concetto di trade-off da quello di costo opportunità?",
    options: [
      {
        id: "a",
        text: "Il costo opportunità coincide con il valore della migliore alternativa a cui si rinuncia quando si effettua una scelta",
        correct: true,
      },
      {
        id: "b",
        text: "Il trade-off descrive una situazione in cui migliorare un obiettivo comporta necessariamente peggiorarne un altro (es. qualità vs costo)",
        correct: true,
      },
      {
        id: "c",
        text: "Trade-off e costo opportunità sono sinonimi perfettamente intercambiabili in ogni contesto decisionale",
        correct: false,
      },
      {
        id: "d",
        text: "Il costo opportunità è sempre pari al solo costo contabile esplicito sostenuto, senza considerare le alternative sacrificate",
        correct: false,
      },
    ],
    explanation: {
      why: "Ogni decisione d'impresa comporta rinunce: misurarle correttamente evita di scegliere l'opzione apparentemente più economica ma in realtà più costosa.",
      what: "Il trade-off è la relazione di scambio tra obiettivi confliggenti; il costo opportunità è la quantificazione della migliore alternativa sacrificata.",
      how: "Corrette (a) e (b). La (c) è errata perché i due concetti operano a livelli diversi (relazione vs misura); la (d) è errata perché ignora proprio le alternative implicite.",
      trap: "Confondere il costo contabile (ciò che pago) con il costo economico (ciò a cui rinuncio).",
    },
    sourceRef: "Slide Blocco I - Impresa e decisioni / Dispensa Teoria dell'Impresa",
  },
  {
    id: "B1-SEED-FT-101",
    version: 1,
    block: 1,
    topic: "definizione-impresa",
    tags: ["art-2082", "imprenditore", "definizione"],
    track: "essential",
    difficulty: 1,
    type: "free-text",
    stem: "Secondo l'art. 2082 del Codice Civile, quale articolo definisce l'imprenditore? Indica il numero dell'articolo e due requisiti dell'attività d'impresa.",
    freeTextKeywords: ["2082", "professionale", "organizzata", "economica"],
    explanation: {
      why: "La definizione giuridica delimita chi è soggetto allo statuto dell'imprenditore (registri, scritture, procedure concorsuali).",
      what: "È imprenditore chi esercita professionalmente un'attività economica organizzata al fine della produzione o dello scambio di beni o di servizi (art. 2082 c.c.).",
      how: "I requisiti chiave sono: professionalità (non occasionalità), organizzazione dei fattori produttivi ed economicità (tendere a coprire i costi con i ricavi).",
      trap: "L'impresa non coincide con l'azienda: l'azienda (art. 2555) è il complesso di beni organizzati, l'impresa è l'attività.",
    },
    sourceRef: "Slide Blocco I - Codice Civile art. 2082 e 2555",
  },
  // ---------------- Blocco 2 ----------------
  {
    id: "B2-SEED-MC-101",
    version: 1,
    block: 2,
    topic: "societa-persone-capitali",
    tags: ["snc", "srl", "responsabilita", "autonomia-patrimoniale"],
    track: "essential",
    difficulty: 2,
    type: "multi-choice",
    stem: "Quali affermazioni descrivono correttamente il regime di responsabilità nelle società di persone e di capitali?",
    options: [
      {
        id: "a",
        text: "Nella S.n.c. i soci rispondono solidalmente e illimitatamente per le obbligazioni sociali, con beneficio di escussione (art. 2304)",
        correct: true,
      },
      {
        id: "b",
        text: "Nella S.r.l. vige l'autonomia patrimoniale perfetta: risponde solo la società con il proprio patrimonio",
        correct: true,
      },
      {
        id: "c",
        text: "Nella S.r.l. ciascun socio risponde sempre con il proprio patrimonio personale dei debiti sociali",
        correct: false,
      },
      {
        id: "d",
        text: "La S.n.c. attribuisce a tutti i soci una responsabilità limitata al solo capitale conferito",
        correct: false,
      },
    ],
    explanation: {
      why: "La scelta della forma giuridica determina l'esposizione patrimoniale personale dell'imprenditore: è la prima decisione di risk management.",
      what: "Autonomia perfetta (S.r.l., S.p.A.): separa patrimonio sociale e personale. Autonomia imperfetta (S.n.c.): i soci rispondono illimitatamente ma i creditori devono prima escutere il patrimonio sociale.",
      how: "Corrette (a) e (b). La (c) descrive le società di persone, non la S.r.l.; la (d) rovescia la disciplina della S.n.c.",
      trap: "Credere che 'società' significhi sempre protezione del patrimonio personale: vale solo per le società di capitali.",
    },
    sourceRef: "Slide Blocco II - Forme giuridiche / Codice Civile art. 2304",
  },
  {
    id: "B2-SEED-FT-101",
    version: 1,
    block: 2,
    topic: "sas-accomandante",
    tags: ["sas", "divieto-immistione", "accomandante"],
    track: "standard",
    difficulty: 2,
    type: "free-text",
    stem: "Nella S.a.s., quale articolo del Codice Civile vieta al socio accomandante di ingerirsi nell'amministrazione (divieto di immistione)? Indica numero e istituto.",
    freeTextKeywords: ["2320", "immistione", "accomandante"],
    explanation: {
      why: "Il divieto tutela i terzi: chi appare come gestore deve rispondere come gestore illimitatamente.",
      what: "L'art. 2320 c.c. vieta all'accomandante atti di amministrazione e trattazione di affari; la violazione comporta responsabilità illimitata e solidale.",
      how: "L'accomandante può solo prestare opera sotto direzione degli accomandatari e votare su decisioni straordinarie.",
      trap: "Confondere accomandante (finanziatore con responsabilità limitata) e accomandatario (gestore illimitatamente responsabile).",
    },
    sourceRef: "Slide Blocco II - S.a.s. / Codice Civile art. 2320",
  },
  // ---------------- Blocco 3 ----------------
  {
    id: "B3-SEED-MC-101",
    version: 1,
    block: 3,
    topic: "patti-parasociali-clausole",
    tags: ["patti-parasociali", "drag-along", "liquidation-preference", "venture-capital"],
    track: "standard",
    difficulty: 2,
    type: "multi-choice",
    stem: "Quali affermazioni descrivono correttamente le clausole tipiche dei patti parasociali nei round di venture capital?",
    options: [
      {
        id: "a",
        text: "La clausola di drag-along consente alla maggioranza di trascinare la minoranza nella vendita a un terzo alle stesse condizioni",
        correct: true,
      },
      {
        id: "b",
        text: "La liquidation preference attribuisce a taluni investitori priorità nella distribuzione dei proventi in caso di exit o liquidazione",
        correct: true,
      },
      {
        id: "c",
        text: "La clausola di tag-along obbliga la minoranza a vendere le proprie quote contro la sua volontà",
        correct: false,
      },
      {
        id: "d",
        text: "I patti parasociali devono sempre essere pubblicati all'interno del bilancio d'esercizio della società",
        correct: false,
      },
    ],
    explanation: {
      why: "Nei round VC il controllo e le vie d'uscita si negoziano prima del versamento: queste clausole decidono chi comanda e chi incassa per primo.",
      what: "Drag-along = diritto di trascinamento della maggioranza; tag-along = diritto della minoranza di accodarsi alla vendita; liquidation preference = priorità distributiva degli investitori.",
      how: "Corrette (a) e (b). La (c) rovescia il tag-along (è un diritto, non un obbligo); la (d) è errata (pubblicità diversa a seconda della quotazione, mai in bilancio).",
      trap: "Confondere drag-along (obbligo di seguire) con tag-along (diritto di seguire).",
    },
    sourceRef: "Slide Blocco III - Finanziamento dell'Innovazione e Venture Capital",
  },
  {
    id: "B3-SEED-FT-101",
    version: 1,
    block: 3,
    topic: "venture-capital-carried",
    tags: ["carried-interest", "venture-capital", "gp-lp"],
    track: "standard",
    difficulty: 2,
    type: "free-text",
    stem: "Come si chiama la quota di extra-profitto (tipicamente intorno al 20% oltre una soglia minima) spettante ai gestori (GP) di un fondo di venture capital?",
    freeTextKeywords: ["carried interest", "carried", "interest"],
    explanation: {
      why: "Allinea gli incentivi tra gestori e investitori: il GP guadagna davvero solo se il fondo batte la soglia.",
      what: "Il carried interest è la partecipazione dei General Partner agli utili del fondo oltre l'hurdle rate, tipicamente il 20%.",
      how: "Struttura tipica: restituzione del capitale ai LP + hurdle (es. 8%), poi 80/20 tra LP e GP sull'eccedenza.",
      trap: "Confonderlo con la management fee (commissione annua ~2% sul capitale, dovuta comunque).",
    },
    sourceRef: "Slide Blocco III - Filiera del Venture Capital (LP, GP, carried interest)",
  },
  // ---------------- Blocco 4 ----------------
  {
    id: "B4-SEED-MC-101",
    version: 1,
    block: 4,
    topic: "principi-redazione-bilancio",
    tags: ["art-2423-bis", "prudenza", "competenza", "bilancio"],
    track: "essential",
    difficulty: 2,
    type: "multi-choice",
    stem: "Quali affermazioni applicano correttamente i principi di redazione del bilancio (art. 2423-bis c.c.)?",
    options: [
      {
        id: "a",
        text: "Il principio di prudenza impone di non iscrivere utili non ancora realizzati, ma di rilevare tutte le perdite anche solo probabili",
        correct: true,
      },
      {
        id: "b",
        text: "Il principio di competenza attribuisce costi e ricavi all'esercizio cui si riferiscono, indipendentemente dalla manifestazione di cassa",
        correct: true,
      },
      {
        id: "c",
        text: "Il principio di competenza consente di rinviare i costi agli esercizi futuri ogni volta che serve per mostrare un utile",
        correct: false,
      },
      {
        id: "d",
        text: "Il principio di prudenza richiede di iscrivere anche gli utili sperati ma non ancora realizzati alla data di chiusura",
        correct: false,
      },
    ],
    explanation: {
      why: "Questi principi impediscono di gonfiare artificialmente il risultato: tutelano creditori e soci di minoranza.",
      what: "Prudenza = asimmetria (perdite probabili sì, utili sperati no). Competenza = correlazione temporale costi-ricavi. Continuità = prospettiva di funzionamento.",
      how: "Corrette (a) e (b). La (c) descrive manipolazione contabile; la (d) viola esattamente la prudenza.",
      trap: "Utile di bilancio e cassa non coincidono proprio per competenza e prudenza: utile non significa liquidità.",
    },
    sourceRef: "Slide Blocco IV - Principi art. 2423-bis / Dispensa BILANCIO",
  },
  {
    id: "B4-SEED-FT-101",
    version: 1,
    block: 4,
    topic: "magazzino-fifo-lifo",
    tags: ["magazzino", "fifo", "lifo", "inflazione"],
    track: "standard",
    difficulty: 2,
    type: "free-text",
    stem: "In fase di prezzi crescenti (inflazione), quale metodo di valutazione del magazzino — FIFO, LIFO o costo medio — determina il valore più alto delle rimanenze finali?",
    freeTextKeywords: ["fifo", "first in"],
    explanation: {
      why: "Il metodo scelto sposta utile tra esercizi e quindi imposte e dividendi distribuibili.",
      what: "Con prezzi crescenti, il FIFO scarica per primi i costi più vecchi (bassi) e lascia in magazzino i costi recenti (alti): rimanenze alte, costo del venduto basso, utile più alto.",
      how: "Il LIFO fa l'opposto (magazzino basso, utile basso); il costo medio pondera i due effetti.",
      trap: "Credere che il metodo sia neutrale: a parità di movimenti fisici, cambia il risultato economico dichiarato.",
    },
    sourceRef: "Slide Blocco IV - Magazzino FIFO/LIFO/CMP in inflazione",
  },
  // ---------------- Blocco 5 ----------------
  {
    id: "B5-SEED-MC-101",
    version: 1,
    block: 5,
    topic: "leva-finanziaria-spread",
    tags: ["leva-finanziaria", "roe", "roi", "spread"],
    track: "standard",
    difficulty: 2,
    type: "multi-choice",
    stem: "Quali affermazioni descrivono correttamente l'effetto della leva finanziaria (ROE = ROI + (ROI − i) × D/E)?",
    options: [
      {
        id: "a",
        text: "Se il ROI supera il costo del debito (i), aumentare il rapporto D/E incrementa il ROE (leva positiva)",
        correct: true,
      },
      {
        id: "b",
        text: "Se il ROI è inferiore al costo del debito (i), l'indebitamento deprime il ROE (leva negativa)",
        correct: true,
      },
      {
        id: "c",
        text: "Il ROE coincide sempre con il ROI, indipendentemente dal livello di indebitamento D/E",
        correct: false,
      },
      {
        id: "d",
        text: "Un ROE molto elevato ottenuto con forte leva finanziaria è sempre segnale di impresa sana e solida",
        correct: false,
      },
    ],
    explanation: {
      why: "La struttura finanziaria può amplificare o distruggere la redditività per gli azionisti: lo spread decide tutto.",
      what: "La formula di Modigliani-Miller scompone il ROE in componente operativa (ROI) più effetto leva: spread (ROI − i) per intensità (D/E).",
      how: "Corrette (a) e (b). La (c) vale solo con D/E = 0; la (d) ignora che la leva amplifica anche il rischio di insolvenza.",
      trap: "ROE alto non significa impresa sana: può nascondere un azzardo da iper-indebitamento.",
    },
    sourceRef: "Slide Blocco V - Formula Modigliani-Miller della leva finanziaria",
  },
  {
    id: "B5-SEED-FT-101",
    version: 1,
    block: 5,
    topic: "indici-liquidita",
    tags: ["current-ratio", "liquidita", "indici"],
    track: "essential",
    difficulty: 1,
    type: "free-text",
    stem: "Quale rapporto tra grandezze dello stato patrimoniale riclassificato definisce il Current Ratio (indice di liquidità generale)?",
    freeTextKeywords: ["attivo corrente", "passivo corrente", "current", "liquidita"],
    explanation: {
      why: "Misura la capacità di far fronte agli impegni a breve con le risorse a breve: primo campanello della crisi di liquidità.",
      what: "Current Ratio = Attivo Corrente / Passività Correnti; valori sopra 1 indicano copertura, sotto 1 tensione.",
      how: "Si legge insieme al Quick Ratio (che esclude il magazzino, meno liquido) e alle durate medie del circolante.",
      trap: "Un Current Ratio alto per magazzino invenduto gonfiato non è liquidità vera: utile senza cassa può fallire.",
    },
    sourceRef: "Slide Blocco V - Indici di liquidità (Current e Quick Ratio)",
  },
  // ---------------- Blocco 6 ----------------
  {
    id: "B6-SEED-MC-101",
    version: 1,
    block: 6,
    topic: "decisioni-breve-periodo",
    tags: ["make-or-buy", "costi-rilevanti", "sunk-cost", "decisioni"],
    track: "standard",
    difficulty: 2,
    type: "multi-choice",
    stem: "Quali affermazioni applicano correttamente la logica dei costi rilevanti nelle decisioni di breve periodo (make-or-buy, ordini speciali)?",
    options: [
      {
        id: "a",
        text: "Nella scelta make-or-buy contano solo i costi differenziali evitabili tra le due alternative",
        correct: true,
      },
      {
        id: "b",
        text: "I costi fissi non evitabili e i costi già sostenuti (sunk) non devono influenzare la decisione di breve periodo",
        correct: true,
      },
      {
        id: "c",
        text: "Il costo pieno unitario (full costing) è sempre la base corretta per valutare un ordine speciale una tantum",
        correct: false,
      },
      {
        id: "d",
        text: "Un ordine speciale va accettato solo se il prezzo offerto copre integralmente il costo pieno unitario di prodotto",
        correct: false,
      },
    ],
    explanation: {
      why: "Nel breve periodo la capacità è data: decidere sui costi pieni distrugge margini che invece coprirebbero i fissi.",
      what: "Contano solo i costi rilevanti (differenziali futuri): prezzo vs costo variabile + eventuali fissi incrementali specifici.",
      how: "Corrette (a) e (b). La (c) e la (d) incorporano fissi comuni irrilevanti e portano a rifiutare ordini con margine di contribuzione positivo.",
      trap: "Il full costing serve per il prezzo di lungo periodo, non per decisioni con capacità inutilizzata.",
    },
    sourceRef: "Slide Blocco VI - Decisioni di breve periodo (Make or Buy, ordini speciali)",
  },
  {
    id: "B6-SEED-FT-101",
    version: 1,
    block: 6,
    topic: "bep-formula",
    tags: ["bep", "punto-pareggio", "margine-contribuzione"],
    track: "essential",
    difficulty: 1,
    type: "free-text",
    stem: "Qual è la formula del punto di pareggio (Break-Even Point) in quantità? Indica numeratore e denominatore.",
    freeTextKeywords: ["costi fissi", "margine", "cf", "p-cv"],
    explanation: {
      why: "Il BEP dice quante unità servono per non perdere: bussola minima di ogni piano operativo.",
      what: "Q* = Costi Fissi / Margine di Contribuzione unitario, dove MdC = prezzo − costo variabile unitario.",
      how: "Sopra Q* ogni unità aggiunge MdC all'utile; sotto, erode la copertura dei fissi.",
      trap: "Confondere margine di contribuzione (p − cv) con utile: il MdC deve prima coprire i fissi.",
    },
    sourceRef: "Slide Blocco VI - Break-Even Point (volume e fatturato)",
  },
  // ---------------- Blocco 7 ----------------
  {
    id: "B7-SEED-MC-101",
    version: 1,
    block: 7,
    topic: "strategie-porter",
    tags: ["porter", "leadership-costo", "differenziazione", "focus"],
    track: "essential",
    difficulty: 2,
    type: "multi-choice",
    stem: "Quali affermazioni descrivono correttamente le strategie competitive generiche di Porter?",
    options: [
      {
        id: "a",
        text: "La leadership di costo richiede economie di scala, controllo rigoroso dei costi ed efficienza operativa",
        correct: true,
      },
      {
        id: "b",
        text: "La focalizzazione concentra l'impresa su un segmento ristretto di mercato servito meglio dei concorrenti generalisti",
        correct: true,
      },
      {
        id: "c",
        text: "Restare 'stuck in the middle' senza una strategia chiara garantisce rendimenti superiori alla media",
        correct: false,
      },
      {
        id: "d",
        text: "La differenziazione si ottiene esclusivamente praticando il prezzo più basso del settore",
        correct: false,
      },
    ],
    explanation: {
      why: "Senza un vantaggio difendibile la concorrenza erode i margini: Porter obbliga a scegliere dove vincere.",
      what: "Tre vie: costo (stesso prodotto, meno costi), differenziazione (prodotto unico, premium price), focus (nicchia dominata).",
      how: "Corrette (a) e (b). La (c) descrive la trappola peggiore (né costo né unicità); la (d) confonde differenziazione con leadership di costo.",
      trap: "Voler fare tutto per tutti: chi non sceglie resta incastrato nel mezzo con margini mediocri.",
    },
    sourceRef: "Slide Blocco VII - Strategie competitive di Porter",
  },
  {
    id: "B7-SEED-FT-101",
    version: 1,
    block: 7,
    topic: "modelli-digitali",
    tags: ["freemium", "modelli-business", "piattaforme"],
    track: "essential",
    difficulty: 1,
    type: "free-text",
    stem: "Come si chiama il modello di business che offre gratuitamente una versione base e fa pagare le funzionalità avanzate (es. Dropbox, Spotify, LinkedIn)?",
    freeTextKeywords: ["freemium", "free"],
    explanation: {
      why: "Ab batte la barriera di adozione a costo marginale quasi zero e monetizza la coda degli utenti intensivi.",
      what: "Il freemium combina free + premium: acquisizione gratuita su larga scala, conversione a pagamento su feature avanzate.",
      how: "Metriche chiave: tasso di conversione free→paying e costo di servizio degli utenti gratuiti vs ricavo medio.",
      trap: "Confonderlo con il free puro senza monetizzazione: senza conversione è solo un costo.",
    },
    sourceRef: "Slide Blocco VII - Modelli digitali (Freemium, SaaS)",
  },
];
