import { Question } from "../types";

export const block1Questions: Question[] = [
  {
    id: "B1-SIS-COMP-001",
    version: 1,
    block: 1,
    topic: "impresa-sistema-complesso",
    tags: ["complicato-vs-complesso", "sistema-aperto", "adattamento", "paradigma-ingegneristico"],
    track: "essential",
    difficulty: 2,
    type: "multi-choice",
    stem: "Quali tra le seguenti affermazioni caratterizzano un sistema 'complesso' a differenza di un sistema meramente 'complicato'?",
    options: [
      {
        id: "a",
        text: "È formato da parti interconnesse il cui comportamento complessivo non è predicibile analiticamente sommando le singole parti (proprietà emergenti)",
        correct: true,
      },
      {
        id: "b",
        text: "Può essere compreso e controllato completamente mediante un algoritmo deterministico a patto di raccogliere sufficienti parametri",
        correct: false,
      },
      {
        id: "c",
        text: "È un sistema aperto che scambia materia, energia e informazione con l'ambiente, auto-organizzandosi e adattandosi retroattivamente",
        correct: true,
      },
      {
        id: "d",
        text: "È tipico dei meccanismi lineari chiusi come un orologio meccanico o un motore a pistoni",
        correct: false,
      },
    ],
    explanation: {
      why: "Un ingegnere informatico è abituato a gestire sistemi complicati (hardware/software con causalità deterministica), ma l'impresa è un sistema complesso in cui intervengono individui, mercati e incertezze non riducibili a un algoritmo.",
      what: "Nel sistema complicato le relazioni causa-effetto sono lineari e scomponibili; nel sistema complesso emergono dinamiche non lineari, retroazioni (feedback loops) e capacità di auto-adattamento all'ambiente.",
      how: "Le affermazioni corrette sono (a) e (c). Le opzioni (b) e (d) descrivono invece archetipi di sistemi complicati ma chiusi e deterministici.",
      trap: "Usare 'complicato' e 'complesso' come sinonimi nel linguaggio comune: in economia d'impresa indicano classi epistemologiche radicalmente opposte.",
    },
    sourceRef: "I-05-03-26-Complicato-vs--complesso.md",
  },
  {
    id: "B1-DEC-OPP-002",
    version: 1,
    block: 1,
    topic: "trade-off-costo-opportunita",
    tags: ["costo-opportunita", "trade-off", "decisioni-manageriali", "allocazione-risorse"],
    track: "standard",
    difficulty: 2,
    type: "single-choice",
    stem: "Uno sviluppatore software decide di rifiutare una consulenza retribuita da 15.000 € per dedicare 2 mesi a tempo pieno allo sviluppo della propria app mobile. Nel calcolo economico della convenienza della scelta, cosa rappresentano i 15.000 €?",
    options: [
      {
        id: "a",
        text: "Un costo sommerso (sunk cost) irrecuperabile",
        correct: false,
      },
      {
        id: "b",
        text: "Il costo opportunità della decisione di sviluppare la propria app",
        correct: true,
      },
      {
        id: "c",
        text: "Un costo variabile di produzione dell'applicazione",
        correct: false,
      },
      {
        id: "d",
        text: "Un ricavo differito legato al modello freemium",
        correct: false,
      },
    ],
    explanation: {
      why: "Ogni decisione aziendale comporta l'allocazione di risorse scarse (tempo, capitale, persone): scegliere un'opzione significa rinunciare al valore della migliore alternativa disponibile.",
      what: "Il costo opportunità è il valore monetario o strategico della migliore alternativa sacrificata quando si effettua una scelta economica.",
      how: "I 15.000 € della consulenza a cui lo sviluppatore rinuncia non sono una spesa viva monetaria, ma il rendimento alternativo sacrificato (costo opportunità) che l'app deve almeno superare per essere conveniente.",
      trap: "Confondere il costo opportunità con un costo monetario effettivo o con un costo sommerso (sunk cost già sostenuto nel passato).",
    },
    sourceRef: "I-05-03-26-Trade-off-vs--costo-opportunita.md",
  },
  {
    id: "B1-CAS-OLI-003",
    version: 1,
    block: 1,
    topic: "caso-olivetti",
    tags: ["Olivetti", "Programma-101", "tecnologia-vs-finanza", "short-termism"],
    track: "advanced",
    difficulty: 3,
    type: "multi-true-false",
    stem: "In merito alle vicende storiche della Olivetti e allo sviluppo della Programma 101 (1964-1965), valuta ciascuna affermazione indicando se è Vera (V) o Falsa (F):",
    multiTrueFalseItems: [
      {
        id: "mtf-oli-1",
        statement: "La Programma 101 fu ideata dal team guidato da Pier Giorgio Perotto e viene storicamente riconosciuta come il primo personal computer commerciale al mondo.",
        isTrue: true,
      },
      {
        id: "mtf-oli-2",
        statement: "La divisione elettronica Olivetti venne ceduta a General Electric perché i microprocessori della P101 risultarono tecnicamente obsoleti rispetto alla concorrenza statunitense.",
        isTrue: false,
      },
      {
        id: "mtf-oli-3",
        statement: "L'intervento del 'gruppo di salvataggio' (Fiat, Mediobanca, IMI) impose la cessione dell'elettronica per far fronte al grave debito contratto con l'acquisizione dell'americana Underwood.",
        isTrue: true,
      },
      {
        id: "mtf-oli-4",
        statement: "La vicenda Olivetti dimostra come l'eccellenza tecnologica garantisca automaticamente il successo industriale anche in presenza di una struttura finanziaria fortemente sbilanciata a breve termine.",
        isTrue: false,
      },
    ],
    explanation: {
      why: "Il caso Olivetti illustra il drammatico scollamento tra eccellenza ingegneristica e vincoli di governance economico-finanziaria.",
      what: "La P101 fu un trionfo ingegneristico assoluto, ma l'azienda era gravata da un debito insostenibile generato dall'acquisizione di Underwood. I creditori e i nuovi azionisti (Valletta, Cuccia) preferirono tagliare la divisione elettronica a lungo termine per salvaguardare il business meccanico tradizionale.",
      how: "1: Vera (Perotto guidò il progetto P101). 2: Falsa (la tecnologia era rivoluzionaria e vinse alla fiera di New York nel 1965). 3: Vera (la cessione fu dettata dall'indebitamento finanziario). 4: Falsa (l'eccellenza tecnica da sola non può compensare il dissesto finanziario).",
      trap: "Attribuire il fallimento industriale a un deficit tecnologico: fu invece causato da miopia manageriale ('short-termism') e da vincoli finanziari esogeni.",
    },
    caseStudyRef: "Olivetti (Programma 101)",
    sourceRef: "I-05-03-26-Sintesi-del-documentario-Olivetti.md",
  },
  {
    id: "B1-DEF-IMP-004",
    version: 1,
    block: 1,
    topic: "definizione-impresa",
    tags: ["art-2082", "imprenditore", "economicita", "organizzazione"],
    track: "essential",
    difficulty: 1,
    type: "true-false",
    stem: "Secondo la definizione giuridica ed economica (art. 2082 Codice Civile), per essere qualificata come impresa è indispensabile che l'attività persegua e realizzi un profitto monetario netto positivo (lucro oggettivo e soggettivo).",
    options: [
      { id: "true", text: "Vero", correct: false },
      { id: "false", text: "Falso", correct: true },
    ],
    explanation: {
      why: "Distingue il concetto di economicità (autosufficienza e pareggio costi/ricavi) da quello di mero scopo di lucro (perseguimento del profitto).",
      what: "L'art. 2082 c.c. definisce imprenditore chi esercita professionalmente un'attività economica organizzata al fine della produzione o dello scambio di beni o servizi. Il requisito essenziale è il metodo economico (attitudine a coprire i costi con i ricavi), non necessariamente il lucro soggettivo (infatti esistono imprese pubbliche, cooperative ed enti no-profit che sono imprese a tutti gli effetti).",
      how: "L'affermazione è Falsa: l'economicità (remunerazione dei fattori produttivi) è condizione necessaria e sufficiente; il profitto speculativo non è requisito indispensabile della qualifica di impresa.",
      trap: "Confondere economicità con lucro: un'impresa sociale o cooperativa che chiude in pareggio è un'impresa a pieno titolo.",
    },
    sourceRef: "I-04-03-26-Economia-impresa.md",
  },
  {
    id: "B1-FREE-STK-005",
    version: 1,
    block: 1,
    topic: "stakeholder-theory",
    tags: ["stakeholder", "shareholder", "finalita-impresa", "responsabilita-sociale"],
    track: "standard",
    difficulty: 2,
    type: "free-text",
    stem: "Quale termine definisce l'insieme di tutti i soggetti interni o esterni (dipendenti, clienti, fornitori, azionisti, comunità locale, banche) che hanno un interesse legittimo o sono influenzati dalle decisioni e dai risultati di un'impresa?",
    freeTextKeywords: ["stakeholder", "portatori di interesse", "stakeholders"],
    explanation: {
      why: "L'impresa non risponde solo agli azionisti (shareholder) ma interagisce con una vasta rete di portatori d'interesse senza i quali non potrebbe operare durevolmente.",
      what: "Il termine 'stakeholder' (teorizzato da Freeman) comprende chiunque detenga una 'posta in gioco' nell'attività aziendale, distinguendo tra stakeholder primari (vitali per la sopravvivenza immediata) e secondari.",
      how: "Il termine corretto è 'stakeholder' (o in italiano 'portatori di interesse').",
      trap: "Confondere 'stakeholder' con 'shareholder' (che designa esclusivamente gli azionisti e soci proprietari del capitale di rischio).",
    },
    sourceRef: "I-04-03-26-Economia-impresa.md",
  },
];
