import { Question } from "../types";

export const block2Questions: Question[] = [
  {
    id: "B2-FOR-AUT-001",
    version: 1,
    block: 2,
    topic: "forme-giuridiche-autonomia",
    tags: ["autonomia-patrimoniale", "societa-persone", "societa-capitali", "responsabilita-illimitata"],
    track: "essential",
    difficulty: 2,
    type: "single-choice",
    stem: "Quale principio fondamentale distingue sul piano giuridico ed economico le 'società di capitali' (S.r.l., S.p.A.) dalle 'società di persone' (S.n.c., S.a.s.)?",
    options: [
      {
        id: "a",
        text: "Le società di capitali possiedono personalità giuridica e autonomia patrimoniale perfetta, per cui i soci rischiano solo il capitale conferito",
        correct: true,
      },
      {
        id: "b",
        text: "Le società di persone possono emettere prestiti obbligazionari convertibili quotati sui mercati regolamentati",
        correct: false,
      },
      {
        id: "c",
        text: "Nelle società di capitali i creditori sociali possono aggredire direttamente il patrimonio personale dei soci prima di rivalersi sulla società",
        correct: false,
      },
      {
        id: "d",
        text: "Nelle società di persone la quota di partecipazione è liberamente trasferibile a terzi senza il consenso unanime degli altri soci",
        correct: false,
      },
    ],
    explanation: {
      why: "La scelta della forma societaria determina se il fallimento o i debiti dell'azienda possono distruggere i risparmi personali e la casa dei fondatori/ingegneri.",
      what: "L'autonomia patrimoniale perfetta nelle società di capitali separa totalmente il patrimonio della società da quello dei soci: per i debiti sociali risponde esclusivamente la società con il proprio patrimonio (art. 2325 e 2462 c.c.).",
      how: "L'opzione corretta è (a). Le società di persone hanno autonomia imperfetta (i soci rispondono con i propri beni personali illimitatamente e solidalmente).",
      trap: "Credere che costituire una S.n.c. costi meno e sia quindi sempre consigliabile: espone i soci al rischio di rovina personale per gli insoluti dell'azienda.",
    },
    sourceRef: "II-12-03-Laboratorio-forme-giuridiche.md",
  },
  {
    id: "B2-SAS-SOCI-002",
    version: 1,
    block: 2,
    topic: "societa-accomandita",
    tags: ["SAS", "accomandatari", "accomandanti", "divieto-immistione"],
    track: "standard",
    difficulty: 2,
    type: "true-false",
    stem: "Nella Società in Accomandita Semplice (S.a.s.), il socio accomandante risponde delle obbligazioni sociali solo nei limiti della quota conferita, purché rispetti il divieto di immistione nella gestione e amministrazione della società.",
    options: [
      { id: "true", text: "Vero", correct: true },
      { id: "false", text: "Falso", correct: false },
    ],
    explanation: {
      why: "La S.a.s. consente di attrarre capitali da soci finanziatori che vogliono limitare il proprio rischio, lasciando la gestione a soci tecnici e operativi.",
      what: "Nella S.a.s. coesistono due categorie di soci: gli accomandatari (amministratori con responsabilità solidale e illimitata) e gli accomandanti (finanziatori con responsabilità limitata alla quota, soggetti a divieto di immistione ex art. 2320 c.c.).",
      how: "L'affermazione è Vera: se il socio accomandante compie atti di amministrazione o tratta affari in nome della società senza specifica procura, perde il beneficio della responsabilità limitata e risponde illimitatamente.",
      trap: "Dimenticare il divieto di immistione: l'accomandante che gestisce l'azienda diventa responsabile con tutto il proprio patrimonio personale.",
    },
    sourceRef: "II-12-03-Laboratorio-forme-giuridiche.md",
  },
  {
    id: "B2-STARTUP-INN-003",
    version: 1,
    block: 2,
    topic: "startup-innovativa",
    tags: ["startup-innovativa", "PMI-innovativa", "D.L.-179/2012", "deroghe-societarie", "crowdfunding"],
    track: "standard",
    difficulty: 3,
    type: "multi-choice",
    stem: "Quali tra i seguenti requisiti o agevolazioni speciali sono previsti dal quadro normativo italiano per le 'Startup Innovative' (D.L. 179/2012)?",
    options: [
      {
        id: "a",
        text: "Divieto di distribuzione degli utili per l'intero periodo di permanenza nella sezione speciale del Registro Imprese (max 5 anni)",
        correct: true,
      },
      {
        id: "b",
        text: "Obbligo di quotarsi sul mercato azionario principale entro 24 mesi dalla costituzione",
        correct: false,
      },
      {
        id: "c",
        text: "Possibilità per la S.r.l. di creare categorie di quote prive di diritto di voto o con diritti non proporzionali e di raccogliere capitale tramite portali di equity crowdfunding",
        correct: true,
      },
      {
        id: "d",
        text: "Soddisfacimento di almeno uno dei 3 criteri: spese R&D ≥ 15%, personale altamente qualificato (PhD/ricercatori/magistrali) o titolarità di privativa industriale/software registrato",
        correct: true,
      },
    ],
    explanation: {
      why: "Il regime delle startup innovative offre agli ingegneri informatici strumenti di finanza straordinaria (work for equity, crowdfunding, classi di quote) prima riservati solo alle grandi S.p.A.",
      what: "Il D.L. 179/2012 introduce una deroga al diritto societario per le S.r.l. innovative: blocco utili, deroghe alla postergazione dei finanziamenti soci, emissione di quote standardizzate e accesso semplificato al crowdfunding.",
      how: "Le opzioni corrette sono (a), (c) e (d). L'opzione (b) è falsa: la quotazione in borsa non è affatto obbligatoria.",
      trap: "Confondere i 3 requisiti alternativi (ne basta uno solo: R&D ≥ 15%, personale qualificato o brevetto/software) con requisiti cumulativi.",
    },
    sourceRef: "V-01-04-26-Finanziamento-start-up.md",
  },
  {
    id: "B2-BENEFIT-CASO-004",
    version: 1,
    block: 2,
    topic: "societa-benefit-bcorp",
    tags: ["Societa-Benefit", "B-Corp", "Davines", "sostenibilita", "duplice-finalita"],
    track: "advanced",
    difficulty: 2,
    type: "single-choice",
    stem: "Qual è la differenza sostanziale tra una 'Società Benefit' (qualifica giuridica italiana, L. 208/2015) e una 'Certified B Corp' (come Davines)?",
    options: [
      {
        id: "a",
        text: "La Società Benefit è una forma giuridica legalmente riconosciuta che inserisce nello statuto il perseguimento di uno o più scopi di beneficio comune accanto al profitto; la B Corp è una certificazione privatistica rilasciata dall'ente no-profit B Lab",
        correct: true,
      },
      {
        id: "b",
        text: "La Società Benefit non può conseguire utili e distribuisce dividendi solo a enti caritatevoli, mentre la B Corp è un'azienda commerciale normale",
        correct: false,
      },
      {
        id: "c",
        text: "Sono sinonimi perfetti e indicano lo stesso atto notarile depositato in Camera di Commercio",
        correct: false,
      },
      {
        id: "d",
        text: "La qualifica di Società Benefit si applica solo alle cooperative sociali mentre la B Corp solo alle multinazionali quotate",
        correct: false,
      },
    ],
    explanation: {
      why: "Nelle moderne strategie d'impresa (ESG e sostenibilità), il vincolo tra profitto e impatto sociale ha valore sia legale vincolante per gli amministratori, sia reputazionale di mercato.",
      what: "La Società Benefit è una forma giuridica prevista dall'ordinamento italiano (gli amministratori hanno il dovere fiduciario statutario di perseguire il beneficio comune). La B Corp è invece un attestato privato concesso dopo audit e superamento di un punteggio rigoroso (BIA).",
      how: "La risposta corretta è (a). Molte aziende eccellenti (come Davines nel materiale di studio) sono sia Società Benefit per legge che B Corp certificate.",
      trap: "Pensare che le Società Benefit siano organizzazioni no-profit: sono società a scopo di lucro che affiancano il beneficio sociale al profitto.",
    },
    sourceRef: "II-11-03-SLIDE-Caso-Ferrari.md",
  },
  {
    id: "B2-CAP-MIN-005",
    version: 1,
    block: 2,
    topic: "capitale-sociale-minimo",
    tags: ["capitale-sociale", "SPA", "SRL", "requisiti-costituzione"],
    track: "essential",
    difficulty: 1,
    type: "single-choice",
    stem: "Quali sono i capitali sociali minimi legali attualmente previsti dall'ordinamento civile italiano per la costituzione ordinaria di una S.r.l. e di una S.p.A.?",
    options: [
      { id: "a", text: "S.r.l.: 10.000 €; S.p.A.: 50.000 €", correct: true },
      { id: "b", text: "S.r.l.: 50.000 €; S.p.A.: 120.000 €", correct: false },
      { id: "c", text: "S.r.l.: 1.000 €; S.p.A.: 10.000 €", correct: false },
      { id: "d", text: "S.r.l.: nessun minimo; S.p.A.: 100.000 €", correct: false },
    ],
    explanation: {
      why: "Il capitale sociale minimo è la garanzia originaria indisponibile posta a tutela dei creditori sociali a fronte dell'autonomia patrimoniale perfetta.",
      what: "Per la S.r.l. ordinaria il capitale sociale minimo è 10.000 € (con possibilità di S.r.l. semplificata a 1 €); per la S.p.A. il limite minimo legale è stato abbassato a 50.000 € (dall'originario 120.000 €).",
      how: "La risposta esatta è (a): 10.000 € per la S.r.l. ordinaria e 50.000 € per la S.p.A.",
      trap: "Ricordare il vecchio limite di 120.000 € per le S.p.A., modificato dal D.L. 91/2014 a 50.000 €.",
    },
    sourceRef: "II-12-03-Laboratorio-forme-giuridiche.md",
  },
];
